Running suite(s): Default
5HELLO WORLD
98%: Checks: 83, Failures: 1, Errors: 0
public.c:352:F:Public:A_Array_sum_and_stuff:0: Assertion 'run_program("int data[5]; def int compute(int x, int y) { return (x*y) + (x-y); } def int main() { int i; int result; i = 0; result = 0; while (i < 5) { data[i] = compute(i, i+1); result = result + data[i]; i = i + 1; } return result; }") == 35' failed: run_program("int data[5]; def int compute(int x, int y) { return (x*y) + (x-y); } def int main() { int i; int result; i = 0; result = 0; while (i < 5) { data[i] = compute(i, i+1); result = result + data[i]; i = i + 1; } return result; }") == 45, 35 == 35
